# Two-Tower Model Configuration

seed: 42

data:
  synthetic_path: "synthetic_interactions.json"
  use_hgt_embeddings: true
  hgt_embeddings_path: "embeddings/hgt_embeddings.pt"
  limit: null
  val_ratio: 0.1
  test_ratio: 0.1
  split_by_user: true
  neg_samples_per_pos: 4
  hard_negative_ratio: 0.5  # Proportion of "hard" negatives vs. random negatives

model:
  hidden_layers: [256, 128]
  output_dim: 64
  dropout: 0.2
  temperature: 0.1
  use_context: false

training:
  num_epochs: 50
  batch_size: 128
  learning_rate: 0.001
  weight_decay: 0.0001
  patience: 5
  num_workers: 4
  use_in_batch_negatives: false

export:
  batch_size: 500
